name: deploy
run-name: deploy to production
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Install railway
        run: npm i -g @railway/cli

      - name: Deploy
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{secrets.RAILWAY_TOKEN}}
          service: ${{secrets.RAILWAY_SERVICE}}
          detach: false
